send_alarm_keystrokes:
  description: Sends keystrokes to the virtual keypad of an alarm control panel.
  fields:
    entity_id:
      description: Name(s) of the entities to send keystrokes to.
      example: "alarm_control_panel.partition_1"
    keystrokes:
      description: String of keystrokes.
      example: "*101#"

trigger_emergency:
  description: Triggers a specific emergency on a Control4 alarm control panel.
  fields:
    entity_id:
      description: Name(s) of the alarm control panel entities.
      example: "alarm_control_panel.security_system"
    emergency_type:
      description: Emergency type supported by the panel (Fire, Medical, Panic, or Police).
      example: "Fire"
